name: Example
options:
  minimumXcodeGenVersion: 2.0.0
  bundleIdPrefix: com.sample.example
  deploymentTarget:
    iOS: 11.0
targets:
  Example:
    type: application
    platform: iOS
    sources: 
      - Example
    settings:
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: ${inherited}
    scheme:
      testTargets:
        - Tests
  Tests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - Tests
    dependencies:
      - target: Example
